runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/(.*)
  static_files: dist/static/\1
  upload: dist/static/(.*)
  expiration: 30s

- url: /sitemap.xml
  static_files: dist/sitemap.xml
  upload: dist/sitemap.xml
  expiration: 30s

- url: /(.*)?
  static_files: dist/index.html
  upload: dist/index.html
  expiration: 30s