runtime: python27
api_version: 1
threadsafe: true

handlers:
  # CSS/JS
  - url: /_next/(.*)
    static_files: dist/_next/\1
    upload: dist/_next/(.*)
    secure: always
    expiration: 30s

  # Static files
  - url: /static/(.*)
    static_files: dist/static/\1
    upload: dist/static/(.*)
    secure: always
    expiration: 30s

  # Index page
  - url: /
    mime_type: text/html
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    expiration: 30s

  # All other pages and paths
  - url: /(.*)
    mime_type: text/html
    static_files: dist/\1
    upload: dist/(.*)
    secure: always
    expiration: 30s
