import YTTrendsMd from './showcase-md/yt-trends.md';
import YTStudio from './showcase-md/yt-studio.md';
import YTCreators from './showcase-md/yt-creators.md';


export const SHOWCASES = [
  {
    title: 'YouTube Trends Top Ten Lists 2022',
    client: 'YouTube',
    role: 'Frontend Engineer',
    img: 'youtube-trends-2022.webp',
    description: YTTrendsMd,
    stack: ['Lit', 'TypeScript', 'SCSS', 'Express.js', 'Webpack'],
    videoId: '3N8kXXzU9-Y',
    siteLink: 'http://youtube.com/trends/2022',
  },
  {
    title: 'U.S. of YouTube',
    client: 'YouTube',
    role: 'Frontend Engineer',
    img: 'youtube-us-of-youtube.webp',
    description: `Lorem ipsum...`,
    stack: ['TypeScript', 'SCSS', 'Jinja2', 'Webpack', 'Python'],
    videoId: '7o4KEQ7vJEc',
    siteLink: 'https://www.youtube.com/intl/en_us/howyoutubeworks/progress-impact/impact/us-of-youtube/',
  },
  {
    title: 'YouTube Creator Economy',
    client: 'YouTube',
    role: 'Frontend Engineer',
    img: 'youtube-creator-economy.webp',
    description: `Lorem ipsum...`,
    stack: ['TypeScript', 'SCSS', 'Jinja2', 'Webpack', 'Python'],
    videoId: 'gveZUoCxNGM',
    siteLink: 'https://www.youtube.com/howyoutubeworks/progress-impact/impact/creator-economy/',
  },
  {
    title: 'YouTube Ads',
    client: 'YouTube',
    role: 'Frontend Engineer',
    img: 'youtube-ads.webp',
    description: `Lorem ipsum...`,
    stack: ['TypeScript', 'SCSS', 'Jinja2', 'Webpack', 'Python'],
    videoId: '9aZZBjkKleA',
    siteLink: 'https://www.youtube.com/ads/video-creation-tips/',
  },
  {
    title: 'YouTube Find My Audience',
    client: 'YouTube',
    role: 'Frontend Engineer',
    img: 'youtube-find-my-audience.webp',
    description: `Lorem ipsum...`,
    stack: ['Python', 'Firebase Database', 'Firebase Cloud Function'],
  },
  {
    title: 'YouTube Studio',
    client: 'YouTube',
    role: 'Frontend Engineer',
    img: 'youtube-studio.webp',
    description: YTStudio,
    stack: ['JavaScript', 'SCSS', 'Jinja2', 'Gulp', 'Python'],
    apis: 'YouTube Data, Blogger, Twitter',
    videoId: 'MqW-GOGS7pI',
  },
  {
    title: 'My Fiber',
    client: 'Google',
    role: 'Frontend Engineer',
    img: 'my-fiber.webp',
    description: "Build a responsive prototype to the designer's pixel-perfect specs for mobile testing using Material design elements.",
    stack: ['AngularJS', 'Firebase Database', 'Google App Engine', 'HTML', 'SCSS'],
    videoId: 'YSMDyjB-LDc',
  },
  {
    title: 'Google Fiber Global Nav',
    client: 'Google',
    role: 'Frontend Engineer',
    img: 'google-fiber-global-nav.webp',
    description: "Design and prototype a simpler, more intuitive, responsive, global navigation that can accomodate for marketing and engineering builds using Material components.",
    stack: ['AngularJS', 'Google App Engine', 'HTML', 'SCSS'],
    videoId: 'Ft9qsS7l52U',
  },
  {
    title: 'YouTube Impact Lab',
    client: 'YouTube',
    role: 'Frontend Engineer',
    img: 'youtube-impact-lab.webp',
    description: "Targeting non-profits, YouTube Impact Lab's mission is to harness YouTube's scale, technology and talent to ignite and sustain movements that drive measurable social change.",
    stack: ['AngularJS', 'Firebase Database', 'Google App Engine', 'HTML', 'SCSS'],
    videoId: 'Xvb6DIUf6MA',
    siteLink: 'https://socialimpact.youtube.com/',
  },
  {
    title: 'YouTube Creators',
    client: 'YouTube',
    role: 'Frontend Engineer',
    img: 'youtube-creators.webp',
    description: YTCreators,
    stack: ['Python', 'Jinja', 'JS', 'SCSS', 'HTML'],
    siteLink: 'https://www.youtube.com/creators/',
    videoId: '0XcOLeOeFEc',
  },
  {
    title: 'YouTube Creators, design concept',
    client: 'YouTube',
    role: 'UX Designer',
    img: 'youtube-creators-design.webp',
    description: "I removed the carousel in favor of an image of a popular YouTube Creator. Mulitples studies have shown that carousels are ineffective for displaying content because most ignore anything after the first frame.\n\nThe copy states exactly what this site is — a resource hub for YouTube creators — with clear calls to action.",
    stack: ['Sketch', 'Photoshop'],
  },
  {
    title: 'Google ACUX Doc Center',
    client: 'Google',
    role: 'Frontend Engineer',
    img: 'acux-doc-center.webp',
    description: "Design and prototype an experience that would make it easy for agencies with one to hundreds of clients to find any document in one centralized, filterable location.\n\nGoogle has an international customer base. This means that transactions with them can involve many different currencies, not just US dollars. This project needed to be able to scale and accommodate for such cases by being smart enough to recognize that and have different actions for different currencies. In this example, there are 2 Brazillian documents that have options to open the document in a new window.",
    stack: ['ACUX specs', 'AngularJS', 'Google App Engine', 'SCSS', 'HTML'],
    videoId: 'd-b98ep59ZQ',
  },
  {
    title: 'YouTube Creators for Change',
    client: 'YouTube',
    role: 'Frontend Engineer',
    img: 'youtube-creators-for-change.webp',
    description: "A global initiative that supports YouTube creators who are tackling social issues and promoting awareness, tolerance and empathy on their YouTube channels.\n\nShowcase YouTube creators who have made significant advancements in addressing awareness on their YouTube channels. This site makes it known that YouTube Creators for Change is truely a global initiative by displaying the creators' country of origin and all of the various global chapters.",
    stack: ['JavaScript', 'SCSS', 'Jinja2', 'Gulp', 'Python'],
    videoId: 'hFdvE1EbOMU',
  },
];
